main:
  - name: "ホーム"
    url: ""
    weight: -110
  - name = "アーカイブ"
    url: "post/rich-content/"
    weight: -109
  - name = "リンク"
    identifier: "Links"
    weight: -108
  - parent: "Links"
    name: "Github"
    url: "https://github.com/mzch"
  - parent: "Links"
    name: "Gitlab"
    url: "https://gitlab.com/letlive"
  - parent: "Links"
    name: "Twitter"
    url: "https://twitter.com/_mzch"
  - name: "About"
    url = "about/"
    weight: -107

# social menu links

social:
  - name: "github"
    type: "social"
    weight: 1
    url = "https://github.com/mzch"
  - name: "gitlab"
    weight: 2
    url: "https://gitlab.com/letlive"
  - name: "twitter"
    weight: 3
    url = "https://twitter.com/_mzch"
  - name: "rss"
    weight: 4
    url: "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "discord"
# url = "https://discord.gg/#"
