main:
  - name: "ホーム"
    url: ""
    weight: -110
  - name: "リンク"
    identifier: "Links"
    weight: -108
  - parent: "Links"
    name: "電脳業務日誌"
    url: "https://loginterests.com/"
  - parent: "Links"
    name: "売国奴お断り"
    url: "https://notraitors.com/"
  - name: "連絡先"
    url: "contact/"
    weight: -107

# social menu links

social:
  - name: "github"
    type: "social"
    weight: 1
    url: "https://github.com/mzch"
  - name: "gitlab"
    weight: 2
    url: "https://gitlab.com/letlive"
  - name: "twitter"
    weight: 3
    url: "https://twitter.com/_mzch"
  - name: "rss"
    weight: 4
    url: "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "discord"
# url = "https://discord.gg/#"
